export const tools = [
  {id:'audience',title:'Audience',
   description:'Audience is who you’re writing for. Knowing your reader helps you choose a tone, vocabulary, and level of detail they’ll understand.',
   points:["Consider your audience’s knowledge when writing. You need to explain unfamiliar ideas and skip what they already know.","Adjust your tone to fit your audience and the situation. A message to a friend can sound more casual than a school announcement.","Think about your audience when planning and revising. Check that your words and examples make sense to the people who will read them."],
   example:[['To a friend','“School’s closed tomorrow.”'],['School announcement','“Due to expected snow, schools and offices will be closed Tuesday.”']],
   note:'The same news, adjusted for different readers.'},
  {id:'purpose',title:'Purpose',
   description:'Purpose is your reason for writing: to inform, persuade, entertain, explain, or describe. It guides what you include and how you organize it.',
   points:["Decide what you want your writing to accomplish. Think about what your reader should know, feel, or do afterward.","Choose an approach that fits your purpose. You can use facts to inform, reasons and evidence to persuade, or scenes to entertain.","Keep your purpose in mind when revising. Include details that support your goal and remove ones that distract from it."],
   example:[['Inform','“The library closes at 3 p.m.”'],['Persuade','“The library should stay open until 5 p.m. so students can study after practice.”']],
   note:'One reports information; the other argues for a change.'},
  {id:'words',title:'Word Choice',
   description:'Word choice, or diction, shapes both meaning and mood. A word has a literal meaning (denotation) and the feelings it suggests (connotation).',
   points:["Choose words that express exactly what you mean. Specific nouns and verbs help your reader picture what you are describing.","Think about the feeling your words create. Words with similar meanings can make your writing sound friendly, formal, or threatening.","Review your word choice when revising. Replace vague language with clear, precise words without making your writing unnecessarily complicated."],
   example:[['Neutral','“The dog walked toward me.”'],['Threatening','“The dog stalked toward me.”']],
   note:'“Stalked” suggests a predator. One verb changes the mood.'},
  {id:'show',title:'Show vs. Tell',
   description:'Telling states an idea directly. Showing uses actions, dialogue, or sensory details so readers can work it out for themselves. Good writing uses both.',
   points:["Use showing for important scenes and emotional moments. Actions, dialogue, and sensory details help readers experience what is happening.","Use telling when you need to move the story forward. You can summarize less important events or explain what happens between scenes.","Decide how much detail each moment needs. Showing everything can slow a story down, while telling everything can make it feel distant."],
   example:[['Tell','“Marcus was nervous.”'],['Show','“Marcus bounced his knee beneath the desk and checked the clock for the fourth time.”']],
   note:'His actions reveal the emotion without naming it.'},
  {id:'devices',title:'Literary Devices',
   description:'Literary devices are techniques that help readers picture a scene or understand a deeper idea. Use them to create a mood, develop a theme, or make a comparison—not just to decorate writing.',
   points:["Think about what you want your reader to see or feel before choosing a literary device. A comparison can clarify an idea, while imagery can make a scene more vivid.","Use literary devices to support the meaning of your writing. They should strengthen an idea or mood rather than make a sentence sound fancy."],
   devices:[['Simile','Compares using “like” or “as.”'],['Metaphor','Describes one thing as another.'],['Personification','Gives human qualities to something nonhuman.'],['Imagery','Appeals to the senses.'],['Foreshadowing','Hints at what will happen later.'],['Symbolism','Uses an object or detail to represent a larger idea.'],['Irony','Creates a contrast between expectations and reality, words and meaning, or what readers and characters know.']],
   example:[['Personification','“The floorboards complained beneath his boots.”']],
   note:'“Complained” makes the creaking house feel alive and uneasy.'},
  {id:'journalism',title:'The Elements of Journalism',
   description:'Journalism shares verified information about events that matter. A strong report helps readers quickly understand what happened and why it’s important.',
   points:["Check your facts before reporting them. Tell readers where your information came from so they can understand and verify your sources.","Write clearly and represent people’s views fairly. Separate facts from opinions and describe relevant perspectives accurately.","Choose a story that matters to your audience. News is often worth reporting because it is timely, relevant, or affects people’s lives.","Begin with a lead that gives the most important news. Readers should quickly understand what happened and who was involved.","Organize the report using the inverted pyramid. Put essential facts first, supporting details next, and background information last."],
   example:[['Fictional news lead','“The student council voted 12–3 on Monday to extend library hours during exam week, according to its meeting minutes.”']],
   note:'The lead gives the key facts and identifies the source.'}
];

