export const tools = [
  {id:'audience',title:'Audience',
   description:'Audience is who you’re writing for. Knowing your reader helps you choose a tone, vocabulary, and level of detail they’ll understand.',
   points:[['Consider their knowledge.','Explain unfamiliar ideas; skip what they already know.'],['Match the situation.','A message to a friend can sound different from a school announcement.'],['Use it when planning and revising.','Check that your words make sense to your intended reader.']],
   example:[['To a friend','“School’s closed tomorrow.”'],['School announcement','“Due to expected snow, schools and offices will be closed Tuesday.”']],
   note:'The same news, adjusted for different readers.'},
  {id:'purpose',title:'Purpose',
   description:'Purpose is your reason for writing: to inform, persuade, entertain, explain, or describe. It guides what you include and how you organize it.',
   points:[['Choose a goal.','What should your reader know, feel, or do?'],['Match your approach.','Use facts to inform, reasons and evidence to persuade, or scenes to entertain.'],['Stay focused.','Keep details that help achieve your goal.']],
   example:[['Inform','“The library closes at 3 p.m.”'],['Persuade','“The library should stay open until 5 p.m. so students can study after practice.”']],
   note:'One reports information; the other argues for a change.'},
  {id:'words',title:'Word Choice',
   description:'Word choice, or diction, shapes both meaning and mood. A word has a literal meaning (denotation) and the feelings it suggests (connotation).',
   points:[['Be precise.','Choose specific nouns and verbs that say exactly what you mean.'],['Consider tone.','Similar words can feel friendly, formal, or threatening.'],['Use it when revising.','Replace vague language without making it needlessly complicated.']],
   example:[['Neutral','“The dog walked toward me.”'],['Threatening','“The dog stalked toward me.”']],
   note:'“Stalked” suggests a predator. One verb changes the mood.'},
  {id:'show',title:'Show vs. Tell',
   description:'Telling states an idea directly. Showing uses actions, dialogue, or sensory details so readers can work it out for themselves. Good writing uses both.',
   points:[['Show key moments.','Use meaningful details to bring scenes and emotions to life.'],['Tell to move faster.','Summarize less important events or connect scenes.'],['Choose for the moment.','Showing everything can slow a story down.']],
   example:[['Tell','“Marcus was nervous.”'],['Show','“Marcus bounced his knee beneath the desk and checked the clock for the fourth time.”']],
   note:'His actions reveal the emotion without naming it.'},
  {id:'devices',title:'Literary Devices',
   description:'Literary devices are techniques that help readers picture a scene or understand a deeper idea. Use them to create a mood, develop a theme, or make a comparison—not just to decorate writing.',
   points:[['Choose an effect.','Decide what you want readers to see or feel.'],['Keep it meaningful.','A device should make the idea clearer or more powerful.']],
   devices:[['Simile','Compares using “like” or “as.”'],['Metaphor','Describes one thing as another.'],['Personification','Gives human qualities to something nonhuman.'],['Imagery','Appeals to the senses.'],['Foreshadowing','Hints at what will happen later.'],['Symbolism','Uses an object or detail to represent a larger idea.'],['Irony','Creates a contrast between expectations and reality, words and meaning, or what readers and characters know.']],
   example:[['Personification','“The floorboards complained beneath his boots.”']],
   note:'“Complained” makes the creaking house feel alive and uneasy.'},
  {id:'journalism',title:'The Elements of Journalism',
   description:'Journalism shares verified information about events that matter. A strong report helps readers quickly understand what happened and why it’s important.',
   points:[['Accuracy & sourcing.','Check facts and say where information came from.'],['Clarity & fairness.','Write plainly, separate fact from opinion, and represent relevant perspectives accurately.'],['Newsworthiness.','Choose stories that are timely, relevant, or affect people.'],['Lead & structure.','Open with the essential news, then add details in order of importance.']],
   example:[['Fictional news lead','“The student council voted 12–3 on Monday to extend library hours during exam week, according to its meeting minutes.”']],
   note:'The lead gives the key facts and identifies the source.'}
];
