import React, { useState, useRef, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import ToolSprite from './ToolSprite';
import './styles.css';
import { guides, devices, journalismElements } from './content';

const tools = [
  {id:'audience', title:'Audience', hint:'Know who’s listening.'},
  {id:'purpose', title:'Purpose', hint:'Find your direction.'},
  {id:'words', title:'Word Choice', hint:'Make every word count.'},
  {id:'show', title:'Show vs. Tell', hint:'Bring the moment to life.'},
  {id:'devices', title:'Literary Devices', hint:'Give your words depth.'},
  {id:'journalism', title:'The Elements of Journalism', hint:'Tell the story. Get it right.'},
];
function Header(){return <header className="header"><div className="eyebrow"><span className="mark">W.</span> WRITER’S FIELD GUIDE</div><span className="edition">SIX TOOLS. ENDLESS POSSIBILITIES.</span></header>}
function ToolItem({tool,index,onSelect}){return <button className={`tool tool-${tool.id}`} onClick={()=>onSelect(tool.id)}><span className="object"><ToolSprite type={tool.id}/></span><span className="tool-label"><span className="number">0{index+1}</span><span className="tool-name">{tool.title}</span><span className="open-arrow" aria-hidden="true">↗</span></span><span className="tool-hint">{tool.hint}</span></button>}
function Toolbox({onSelect}) {return <><section className="intro"><div><div className="small-caption">GOOD WRITING IS A CRAFT.</div><h1>THE WRITER’S<br/>TOOLBOX<span className="title-period">.</span></h1></div><p>An interactive guide to the tools writers use to shape ideas, communicate clearly, and create effective writing.</p></section><section className="workbench" aria-label="Six writing tools"><div className="bench-top"><span>YOUR WORKBENCH</span><span>Pick a tool. Build a better sentence.</span></div><div className="tool-grid">{tools.map((tool,index)=><ToolItem key={tool.id} {...{tool,index,onSelect}}/>)}</div><div className="bench-bottom"><span>A FEW GOOD TOOLS GO A LONG WAY.</span><span className="bench-line"/><span>01 — 06</span></div></section><footer><span>Made for the practice of writing.</span><span>Keep this guide close. Make it your own.</span></footer></>}
function GuideSection({title,children}){return <section className="guide-section"><h2>{title}</h2><p>{children}</p></section>}
function LiteraryDeviceList(){return <section className="device-list"><div className="section-kicker">A CLOSER LOOK</div><h2>Seven ways to shape meaning.</h2>{devices.map(([name,definition,example,why],i)=><details key={name}><summary><span className="number">0{i+1}</span><span>{name}</span><span className="expand-symbol" aria-hidden="true"/></summary><div className="device-content"><p>{definition}</p><blockquote>{example}</blockquote><p className="device-why">{why}</p></div></details>)}</section>}
function Journalism(){return <section className="news-section"><div className="news-masthead"><span>THE REPORTER’S NOTEBOOK</span><span>FACTS FIRST.</span></div><h2>A story readers can trust.</h2><div className="news-columns"><div>{journalismElements.map(([title,copy])=><section className="news-element" key={title}><h3>{title}</h3><p>{copy}</p></section>)}</div><figure className="pyramid"><figcaption>THE INVERTED PYRAMID</figcaption><div className="pyramid-shape">{['Most important information','Important details','Background / context','Less essential details'].map((label,i)=><React.Fragment key={label}><div className={`pyramid-level level-${i}`}>{label}</div>{i<3&&<span aria-hidden="true">↓</span>}</React.Fragment>)}</div><p>Lead with what matters most.<br/>Add depth as the story continues.</p></figure></div></section>}
function GuideView({tool,onBack}){const data=guides[tool.id];const heading=useRef(null);useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[tool.id]);return <article className={`guide guide-${tool.id}`}><button className="back-button" onClick={onBack}>← <span>Back to Toolbox</span></button><div className="guide-header"><div><div className="section-kicker">TOOL 0{tools.indexOf(tool)+1} / 06</div><h1 ref={heading} tabIndex={-1}>{tool.title}</h1><p>{data.subtitle}</p></div><div className="guide-object"><ToolSprite type={tool.id}/></div></div><div className="guide-body"><div className="guide-explanation"><GuideSection title="What is it?">{data.what}</GuideSection><GuideSection title="How does it work?">{data.how}</GuideSection><GuideSection title="When and why should writers use it?">{data.when}</GuideSection></div><aside className="example"><span className="section-kicker">IN PRACTICE</span><h2>{tool.id === 'journalism' ? <>The story, in<br/>one sentence.</> : <>A small change.<br/>A different effect.</>}</h2>{data.examples.map(([label,quote])=><div className="example-item" key={label}><h3>{label}</h3><blockquote>{quote}</blockquote></div>)}<p className="takeaway">{data.takeaway}</p></aside></div>{tool.id==='devices'&&<LiteraryDeviceList/>}{tool.id==='journalism'&&<Journalism/>}<div className="field-note"><span className="section-kicker">KEEP IN MIND</span><p>{data.prompt}</p></div><div className="guide-end"><button className="back-button" onClick={onBack}>← <span>Back to Toolbox</span></button><span>ONE TOOL. A MORE INTENTIONAL DRAFT.</span></div></article>}
function App(){const [selected,setSelected]=useState(null);const previous=useRef(null);const scrollPosition=useRef(0);function select(id){previous.current=document.activeElement;scrollPosition.current=window.scrollY;setSelected(id)}function back(){setSelected(null);requestAnimationFrame(()=>{window.scrollTo(0,scrollPosition.current);document.querySelector(`.tool-${selected}`)?.focus({preventScroll:true})})}useEffect(()=>{function escape(event){if(event.key==='Escape'&&selected)back()}window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[selected]);return <div className="site"><Header/><main>{selected?<GuideView key={selected} tool={tools.find(t=>t.id===selected)} onBack={back}/>:<Toolbox onSelect={select}/>}</main></div>}
createRoot(document.getElementById('root')).render(<App/>);
